package java.rmi.server

import java.io.IOException
import java.lang.{Deprecated, Exception, Object, String, Throwable}
import java.rmi.RemoteException
import scala.scalanative.annotation.stub

/** This exception is thrown when a call is received that does not
 *  match the available skeleton.  It indicates either that the
 *  remote method names or signatures in this interface have changed or
 *  that the stub class used to make the call and the skeleton
 *  receiving the call were not generated by the same version of
 *  the stub compiler (rmic).
 */
@Deprecated class SkeletonMismatchException extends RemoteException {

    /** Deprecated. 
     * no replacement
     * 
     */
    @stub
    def this(s: String) = ???
}
