package javax.print.attribute.standard

import java.lang.{Class, Object, String}
import javax.print.attribute.{Attribute, DocAttribute, EnumSyntax, PrintJobAttribute, PrintRequestAttribute}

// Class OrientationRequested is a printing attribute class, an enumeration,
// that indicates the desired orientation for printed print-stream pages; it
// does not describe the orientation of the client-supplied print-stream
// pages.
// 
// For some document formats (such as "application/postscript"),
// the desired orientation of the print-stream pages is specified within the
// document data. This information is generated by a device driver prior to
// the submission of the print job. Other document formats (such as
// "text/plain") do not include the notion of desired orientation
// within the document data. In the latter case it is possible for the printer
// to bind the desired orientation to the document data after it has been
// submitted. It is expected that a printer would only support the
// OrientationRequested attribute for some document formats (e.g.,
// "text/plain" or "text/html") but not others (e.g.
// "application/postscript"). This is no different from any other
// job template attribute, since a print job can always impose constraints
// among the values of different job template attributes.
//  However, a special mention
// is made here since it is very likely that a printer will support the
// OrientationRequested attribute for only a subset of the supported document
// formats.
// 
// IPP Compatibility: The category name returned by
// getName() is the IPP attribute name.  The enumeration's
// integer value is the IPP enum value.  The toString() method
// returns the IPP string representation of the attribute value.
// 
final class OrientationRequested extends EnumSyntax with DocAttribute, with PrintRequestAttribute, with PrintJobAttribute {

    @stub
    // Get the printing attribute class which is to be used as the "category"
    // for this printing attribute value.
    def getCategory(): Class[_ <: Attribute] = ???

    @stub
    // Returns the enumeration value table for class OrientationRequested.
    protected def getEnumValueTable(): Array[EnumSyntax] = ???

    @stub
    // Get the name of the category of which this attribute value is an
    // instance.
    def getName(): String = ???

    @stub
    // Returns the lowest integer value used by class OrientationRequested.
    protected def getOffset(): Int = ???
}

object OrientationRequested {
    @stub
    // The content will be imaged across the long edge of the medium.
    def LANDSCAPE: OrientationRequested = ???

    @stub
    // The content will be imaged across the short edge of the medium.
    def PORTRAIT: OrientationRequested = ???

    @stub
    // The content will be imaged across the long edge of the medium, but in
    // the opposite manner from landscape.
    def REVERSE_LANDSCAPE: OrientationRequested = ???
}
