package javax.print.attribute.standard

import java.lang.{Class, Object}
import javax.print.attribute.{Attribute, IntegerSyntax, PrintServiceAttribute}

/** Class PagesPerMinute is an integer valued printing attribute that indicates
 *  the nominal number of pages per minute to the nearest whole number which may
 *  be generated by this printer (e.g., simplex, black-and-white). This attribute
 *  is informative, not a service guarantee. Generally, it is the value used in
 *  the marketing literature to describe the device. A value of 0 indicates a
 *  device that takes more than two minutes to process a page.
 *  
 *  IPP Compatibility: The integer value gives the IPP integer value. The
 *  category name returned by getName() gives the IPP attribute
 *  name.
 *  
 */
final class PagesPerMinute extends IntegerSyntax with PrintServiceAttribute {

    /** Returns whether this pages per minute attribute is equivalent to the
     *  passed in object.
     */
    @stub
    def equals(object: Object): Boolean = ???

    /** Get the printing attribute class which is to be used as the "category"
     *  for this printing attribute value.
     */
    @stub
    def getCategory(): Class[_ <: Attribute] = ???
}
