package javax.swing.plaf.multi

import java.awt.{Dimension, Graphics}
import java.io.File
import java.lang.{Object, String}
import javax.accessibility.Accessible
import javax.swing.{JComponent, JFileChooser}
import javax.swing.filechooser.{FileFilter, FileView}
import javax.swing.plaf.{ComponentUI, FileChooserUI}

// A multiplexing UI used to combine FileChooserUIs.
//
// This file was automatically generated by AutoMulti.
class MultiFileChooserUI extends FileChooserUI {

    @stub
    // Invokes the contains method on each UI handled by this object.
    def contains(a: JComponent, b: Int, c: Int): Boolean = ???

    @stub
    // Invokes the ensureFileIsVisible method on each UI handled by this object.
    def ensureFileIsVisible(a: JFileChooser, b: File): Unit = ???

    @stub
    // Invokes the getAcceptAllFileFilter method on each UI handled by this object.
    def getAcceptAllFileFilter(a: JFileChooser): FileFilter = ???

    @stub
    // Invokes the getAccessibleChild method on each UI handled by this object.
    def getAccessibleChild(a: JComponent, b: Int): Accessible = ???

    @stub
    // Invokes the getAccessibleChildrenCount method on each UI handled by this object.
    def getAccessibleChildrenCount(a: JComponent): Int = ???

    @stub
    // Invokes the getApproveButtonText method on each UI handled by this object.
    def getApproveButtonText(a: JFileChooser): String = ???

    @stub
    // Invokes the getDialogTitle method on each UI handled by this object.
    def getDialogTitle(a: JFileChooser): String = ???

    @stub
    // Invokes the getFileView method on each UI handled by this object.
    def getFileView(a: JFileChooser): FileView = ???

    @stub
    // Invokes the getMaximumSize method on each UI handled by this object.
    def getMaximumSize(a: JComponent): Dimension = ???

    @stub
    // Invokes the getMinimumSize method on each UI handled by this object.
    def getMinimumSize(a: JComponent): Dimension = ???

    @stub
    // Invokes the getPreferredSize method on each UI handled by this object.
    def getPreferredSize(a: JComponent): Dimension = ???

    @stub
    // Returns the list of UIs associated with this multiplexing UI.
    def getUIs(): Array[ComponentUI] = ???

    @stub
    // Invokes the installUI method on each UI handled by this object.
    def installUI(a: JComponent): Unit = ???

    @stub
    // Invokes the paint method on each UI handled by this object.
    def paint(a: Graphics, b: JComponent): Unit = ???

    @stub
    // Invokes the rescanCurrentDirectory method on each UI handled by this object.
    def rescanCurrentDirectory(a: JFileChooser): Unit = ???

    @stub
    // Invokes the uninstallUI method on each UI handled by this object.
    def uninstallUI(a: JComponent): Unit = ???
}

object MultiFileChooserUI {
    @stub
    // Returns a multiplexing UI instance if any of the auxiliary
    // LookAndFeels supports this UI.
    def createUI(a: JComponent): ComponentUI = ???
}
