package javax.swing.plaf.multi

import java.awt.{Dimension, Graphics}
import java.io.File
import java.lang.{Object, String}
import javax.accessibility.Accessible
import javax.swing.{JComponent, JFileChooser}
import javax.swing.filechooser.{FileFilter, FileView}
import javax.swing.plaf.{ComponentUI, FileChooserUI}

/** A multiplexing UI used to combine FileChooserUIs.
 * 
 *  This file was automatically generated by AutoMulti.
 */
class MultiFileChooserUI extends FileChooserUI {

    /** Invokes the contains method on each UI handled by this object. */
    @stub
    def contains(a: JComponent, b: Int, c: Int): Boolean = ???

    /** Invokes the ensureFileIsVisible method on each UI handled by this object. */
    @stub
    def ensureFileIsVisible(a: JFileChooser, b: File): Unit = ???

    /** Invokes the getAcceptAllFileFilter method on each UI handled by this object. */
    @stub
    def getAcceptAllFileFilter(a: JFileChooser): FileFilter = ???

    /** Invokes the getAccessibleChild method on each UI handled by this object. */
    @stub
    def getAccessibleChild(a: JComponent, b: Int): Accessible = ???

    /** Invokes the getAccessibleChildrenCount method on each UI handled by this object. */
    @stub
    def getAccessibleChildrenCount(a: JComponent): Int = ???

    /** Invokes the getApproveButtonText method on each UI handled by this object. */
    @stub
    def getApproveButtonText(a: JFileChooser): String = ???

    /** Invokes the getDialogTitle method on each UI handled by this object. */
    @stub
    def getDialogTitle(a: JFileChooser): String = ???

    /** Invokes the getFileView method on each UI handled by this object. */
    @stub
    def getFileView(a: JFileChooser): FileView = ???

    /** Invokes the getMaximumSize method on each UI handled by this object. */
    @stub
    def getMaximumSize(a: JComponent): Dimension = ???

    /** Invokes the getMinimumSize method on each UI handled by this object. */
    @stub
    def getMinimumSize(a: JComponent): Dimension = ???

    /** Invokes the getPreferredSize method on each UI handled by this object. */
    @stub
    def getPreferredSize(a: JComponent): Dimension = ???

    /** Returns the list of UIs associated with this multiplexing UI. */
    @stub
    def getUIs(): Array[ComponentUI] = ???

    /** Invokes the installUI method on each UI handled by this object. */
    @stub
    def installUI(a: JComponent): Unit = ???

    /** Invokes the paint method on each UI handled by this object. */
    @stub
    def paint(a: Graphics, b: JComponent): Unit = ???

    /** Invokes the rescanCurrentDirectory method on each UI handled by this object. */
    @stub
    def rescanCurrentDirectory(a: JFileChooser): Unit = ???

    /** Invokes the uninstallUI method on each UI handled by this object. */
    @stub
    def uninstallUI(a: JComponent): Unit = ???
}

object MultiFileChooserUI {
    /** Returns a multiplexing UI instance if any of the auxiliary
     *  LookAndFeels supports this UI.
     */
    @stub
    def createUI(a: JComponent): ComponentUI = ???
}
