package javax.swing.plaf.multi

import java.awt.{Dimension, Graphics, Rectangle}
import java.lang.Object
import javax.accessibility.Accessible
import javax.swing.{JComponent, JTree}
import javax.swing.plaf.{ComponentUI, TreeUI}
import javax.swing.tree.TreePath

// A multiplexing UI used to combine TreeUIs.
//
// This file was automatically generated by AutoMulti.
class MultiTreeUI extends TreeUI {

    @stub
    // Invokes the cancelEditing method on each UI handled by this object.
    def cancelEditing(a: JTree): Unit = ???

    @stub
    // Invokes the contains method on each UI handled by this object.
    def contains(a: JComponent, b: Int, c: Int): Boolean = ???

    @stub
    // Invokes the getAccessibleChild method on each UI handled by this object.
    def getAccessibleChild(a: JComponent, b: Int): Accessible = ???

    @stub
    // Invokes the getAccessibleChildrenCount method on each UI handled by this object.
    def getAccessibleChildrenCount(a: JComponent): Int = ???

    @stub
    // Invokes the getClosestPathForLocation method on each UI handled by this object.
    def getClosestPathForLocation(a: JTree, b: Int, c: Int): TreePath = ???

    @stub
    // Invokes the getEditingPath method on each UI handled by this object.
    def getEditingPath(a: JTree): TreePath = ???

    @stub
    // Invokes the getMaximumSize method on each UI handled by this object.
    def getMaximumSize(a: JComponent): Dimension = ???

    @stub
    // Invokes the getMinimumSize method on each UI handled by this object.
    def getMinimumSize(a: JComponent): Dimension = ???

    @stub
    // Invokes the getPathBounds method on each UI handled by this object.
    def getPathBounds(a: JTree, b: TreePath): Rectangle = ???

    @stub
    // Invokes the getPathForRow method on each UI handled by this object.
    def getPathForRow(a: JTree, b: Int): TreePath = ???

    @stub
    // Invokes the getPreferredSize method on each UI handled by this object.
    def getPreferredSize(a: JComponent): Dimension = ???

    @stub
    // Invokes the getRowCount method on each UI handled by this object.
    def getRowCount(a: JTree): Int = ???

    @stub
    // Invokes the getRowForPath method on each UI handled by this object.
    def getRowForPath(a: JTree, b: TreePath): Int = ???

    @stub
    // Returns the list of UIs associated with this multiplexing UI.
    def getUIs(): Array[ComponentUI] = ???

    @stub
    // Invokes the installUI method on each UI handled by this object.
    def installUI(a: JComponent): Unit = ???

    @stub
    // Invokes the isEditing method on each UI handled by this object.
    def isEditing(a: JTree): Boolean = ???

    @stub
    // Invokes the paint method on each UI handled by this object.
    def paint(a: Graphics, b: JComponent): Unit = ???

    @stub
    // Invokes the startEditingAtPath method on each UI handled by this object.
    def startEditingAtPath(a: JTree, b: TreePath): Unit = ???

    @stub
    // Invokes the stopEditing method on each UI handled by this object.
    def stopEditing(a: JTree): Boolean = ???

    @stub
    // Invokes the uninstallUI method on each UI handled by this object.
    def uninstallUI(a: JComponent): Unit = ???
}

object MultiTreeUI {
    @stub
    // Returns a multiplexing UI instance if any of the auxiliary
    // LookAndFeels supports this UI.
    def createUI(a: JComponent): ComponentUI = ???
}
