package javax.swing.plaf.multi

import java.awt.{Dimension, Graphics}
import java.lang.Object
import javax.accessibility.Accessible
import javax.swing.{JComponent, JSplitPane}
import javax.swing.plaf.{ComponentUI, SplitPaneUI}

/** A multiplexing UI used to combine SplitPaneUIs.
 * 
 *  This file was automatically generated by AutoMulti.
 */
class MultiSplitPaneUI extends SplitPaneUI {

    /** Invokes the contains method on each UI handled by this object. */
    @stub
    def contains(a: JComponent, b: Int, c: Int): Boolean = ???

    /** Invokes the finishedPaintingChildren method on each UI handled by this object. */
    @stub
    def finishedPaintingChildren(a: JSplitPane, b: Graphics): Unit = ???

    /** Invokes the getAccessibleChild method on each UI handled by this object. */
    @stub
    def getAccessibleChild(a: JComponent, b: Int): Accessible = ???

    /** Invokes the getAccessibleChildrenCount method on each UI handled by this object. */
    @stub
    def getAccessibleChildrenCount(a: JComponent): Int = ???

    /** Invokes the getDividerLocation method on each UI handled by this object. */
    @stub
    def getDividerLocation(a: JSplitPane): Int = ???

    /** Invokes the getMaximumDividerLocation method on each UI handled by this object. */
    @stub
    def getMaximumDividerLocation(a: JSplitPane): Int = ???

    /** Invokes the getMaximumSize method on each UI handled by this object. */
    @stub
    def getMaximumSize(a: JComponent): Dimension = ???

    /** Invokes the getMinimumDividerLocation method on each UI handled by this object. */
    @stub
    def getMinimumDividerLocation(a: JSplitPane): Int = ???

    /** Invokes the getMinimumSize method on each UI handled by this object. */
    @stub
    def getMinimumSize(a: JComponent): Dimension = ???

    /** Invokes the getPreferredSize method on each UI handled by this object. */
    @stub
    def getPreferredSize(a: JComponent): Dimension = ???

    /** Returns the list of UIs associated with this multiplexing UI. */
    @stub
    def getUIs(): Array[ComponentUI] = ???

    /** Invokes the installUI method on each UI handled by this object. */
    @stub
    def installUI(a: JComponent): Unit = ???

    /** Invokes the paint method on each UI handled by this object. */
    @stub
    def paint(a: Graphics, b: JComponent): Unit = ???

    /** Invokes the resetToPreferredSizes method on each UI handled by this object. */
    @stub
    def resetToPreferredSizes(a: JSplitPane): Unit = ???

    /** Invokes the setDividerLocation method on each UI handled by this object. */
    @stub
    def setDividerLocation(a: JSplitPane, b: Int): Unit = ???

    /** Invokes the uninstallUI method on each UI handled by this object. */
    @stub
    def uninstallUI(a: JComponent): Unit = ???
}

object MultiSplitPaneUI {
    /** Returns a multiplexing UI instance if any of the auxiliary
     *  LookAndFeels supports this UI.
     */
    @stub
    def createUI(a: JComponent): ComponentUI = ???
}
