package java.awt.event

import java.awt.{AWTEvent, Component}
import java.lang.Object
import java.util.EventObject

// A low-level event which indicates that a component moved, changed
// size, or changed visibility (also, the root class for the other
// component-level events).
// 
// Component events are provided for notification purposes ONLY;
// The AWT will automatically handle component moves and resizes
// internally so that GUI layout works properly regardless of
// whether a program is receiving these events or not.
// 
// In addition to serving as the base class for other component-related
// events (InputEvent, FocusEvent, WindowEvent, ContainerEvent),
// this class defines the events that indicate changes in
// a component's size, position, or visibility.
// 
// This low-level event is generated by a component object (such as a
// List) when the component is moved, resized, rendered invisible, or made
// visible again. The event is passed to every ComponentListener
// or ComponentAdapter object which registered to receive such
// events using the component's addComponentListener method.
// (ComponentAdapter objects implement the
// ComponentListener interface.) Each such listener object
// gets this ComponentEvent when the event occurs.
// 
// An unspecified behavior will be caused if the id parameter
// of any particular ComponentEvent instance is not
// in the range from COMPONENT_FIRST to COMPONENT_LAST.
class ComponentEvent extends AWTEvent {

    @stub
    // Returns the originator of the event.
    def getComponent(): Component = ???
}

object ComponentEvent {
    @stub
    // The first number in the range of ids used for component events.
    def COMPONENT_FIRST: Int = ???

    @stub
    // This event indicates that the component was rendered invisible.
    def COMPONENT_HIDDEN: Int = ???

    @stub
    // The last number in the range of ids used for component events.
    def COMPONENT_LAST: Int = ???

    @stub
    // This event indicates that the component's position changed.
    def COMPONENT_MOVED: Int = ???

    @stub
    // This event indicates that the component's size changed.
    def COMPONENT_RESIZED: Int = ???
}
