package java.awt.event

import java.awt.{AWTEvent, Window}
import java.lang.Object
import java.util.EventObject

// A low-level event that indicates that a window has changed its status. This
// low-level event is generated by a Window object when it is opened, closed,
// activated, deactivated, iconified, or deiconified, or when focus is
// transfered into or out of the Window.
// 
// The event is passed to every WindowListener
// or WindowAdapter object which registered to receive such
// events using the window's addWindowListener method.
// (WindowAdapter objects implement the
// WindowListener interface.) Each such listener object
// gets this WindowEvent when the event occurs.
// 
// An unspecified behavior will be caused if the id parameter
// of any particular WindowEvent instance is not
// in the range from WINDOW_FIRST to WINDOW_LAST.
class WindowEvent extends ComponentEvent {

    @stub
    // Constructs a WindowEvent object.
    def this(source: Window, id: Int) = ???

    @stub
    // Constructs a WindowEvent object with the specified
    // previous and new window states.
    def this(source: Window, id: Int, oldState: Int, newState: Int) = ???

    @stub
    // Constructs a WindowEvent object with the
    // specified opposite Window.
    def this(source: Window, id: Int, opposite: Window) = ???

    @stub
    // For WINDOW_STATE_CHANGED events returns the
    // new state of the window.
    def getNewState(): Int = ???

    @stub
    // For WINDOW_STATE_CHANGED events returns the
    // previous state of the window.
    def getOldState(): Int = ???

    @stub
    // Returns the other Window involved in this focus or activation change.
    def getOppositeWindow(): Window = ???

    @stub
    // Returns the originator of the event.
    def getWindow(): Window = ???
}

object WindowEvent {
    @stub
    // The window-activated event type.
    def WINDOW_ACTIVATED: Int = ???

    @stub
    // The window closed event.
    def WINDOW_CLOSED: Int = ???

    @stub
    // The "window is closing" event.
    def WINDOW_CLOSING: Int = ???

    @stub
    // The window-deactivated event type.
    def WINDOW_DEACTIVATED: Int = ???

    @stub
    // The window deiconified event type.
    def WINDOW_DEICONIFIED: Int = ???

    @stub
    // The first number in the range of ids used for window events.
    def WINDOW_FIRST: Int = ???

    @stub
    // The window-gained-focus event type.
    def WINDOW_GAINED_FOCUS: Int = ???

    @stub
    // The window iconified event.
    def WINDOW_ICONIFIED: Int = ???

    @stub
    // The last number in the range of ids used for window events.
    def WINDOW_LAST: Int = ???

    @stub
    // The window-lost-focus event type.
    def WINDOW_LOST_FOCUS: Int = ???

    @stub
    // The window opened event.
    def WINDOW_OPENED: Int = ???
}
